apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Values.deployment.name }}
  labels:
    app:  {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app:  {{ .Values.deployment.name }}
    spec:
      containers:
      - name:  {{ .Values.deployment.name }}
        image:  {{ .Values.image.name }}:{{ .Values.image.tag }}
        ports:
        - containerPort:  {{ .Values.image.port }}